spring.application.name=AutoEscola3ESR

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/autoescola3esr
spring.datasource.username=root
spring.datasource.password=fiap

api.security.token.secret=12345678